### PR TITLE
Fix/various

### LINKED ISSUE #132: Edits to CSTK Token Dapp UI
Great work on the dapp all! Just a few edits I would suggest at the bottom of the dapp, as highlighted in the image below.

1. Update "FOR YOUR CONTRIBUTION YOU WILL ALSO RECEIVE:" to **"Your CSTK Score enables:"**

2. Update "Governance Rights" to **"Participation in Community Governance"**

3. Update "Access to Future ABC Hatch Phases" to **"Access to Future Commons Hatches"**

4. Update "Membership in Swiss Commons Stack Associations" to **"Membership in Commons Stack Swiss Association"**

image

### PR DESCRIPTION
**Pull request by MerlinEgalite**
Fix #132, #148, #150, #151

### CODE REVIEW

File: src/pages/contribute/components/Tooltip.js [hunk 1]
```diff
@@ -1,8 +1,7 @@
 import React from 'react';
-import './ToolTip.sass';
-import './DonateModal.sass';
+import './Tooltip.sass';
```
Comment (mendesfabio) [inline src/pages/contribute/components/Tooltip.js:2]:
```suggestion
import './ToolTip.sass';
```

You need to change this or rename the file.

**Review by mendesfabio — CHANGES_REQUESTED** [review]

File: src/pages/contribute/components/Tooltip.js (hunk 1 above)
Comment (MerlinEgalite) [reply src/pages/contribute/components/Tooltip.js:2]: Hm there was a bug with git and renaming the file. I fixed it, thank you!
